# Copy to bae.config.yaml and tweak. Values can be overridden by CLI flags.
product_name: "Data Lineage by Manta"
product_path:
  - IBM
  - IBM Software
  - Data Platform
  - Data Fabric
  - Data Intelligence & Data Integration
  - Data Intelligence
  - Master Data Management Family
  - Data Lineage by Manta
account: bigblue
auth:
  # Put your Aha! API token here for local dev (file is not committed if in .gitignore).
  # Alternatively, set BAE_AHA_TOKEN env var.
  token: ""
filters:
  releases:
    - "Q1 2026 - IKC 5.3.1 and DI 2.3.1"
    - "February SaaS"
    - "June 2026 - IKC 5.4 and DI 2.4"
    - "Plan to remove -- Q3 2026"
    - "Dec 2026 - IKC 5.5 and DI 2.5"
  tags_include:
    - scanners
  tags_one_of:
    - "lineage dev commited"
  # Comma-separated list supported
  pm_owner: "wojciech.smajda@ibm.com, Yurii.Plakhtii@ibm.com"
fields:
  solution_value_statement: solution_value_statement
  risk_status: risk_status
  commitment: commitment
  master_epic: master_epic
  github_link:
    - github_link
    - integrations_to
  product_management_owner: product_management_owner
  development_owner: development_owner
  ibm_software_gtm_themes: ibm_software_gtm_themes
  priority_data_ai: priority_data_ai
